// Dependency-free logic/DOM-stub regression checks. This is not browser visual QA.
const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const sourceDir = process.argv[2] || path.join(__dirname, '..');
let source = fs.readFileSync(path.join(sourceDir, 'index.js'), 'utf8');
const storage = new Map(), timers = new Map(), nodes = new Map();
let timerId = 0, opens = 0;
class Element {
  constructor(tag = 'div') {
    this.tagName = tag.toUpperCase(); this.children = []; this.attrs = {}; this.dataset = {}; this.events = {};
    this.style = {setProperty(k,v){this[k]=v;}}; this.className = ''; this.textContent = ''; this.disabled = false;
    this.classList = {contains: c => this.className.split(' ').includes(c), add: c => {if(!this.classList.contains(c))this.className += ' '+c;},
      remove: c => {this.className=this.className.split(' ').filter(x=>x!==c).join(' ');},
      toggle: (c,on) => {on ??= !this.classList.contains(c); this.classList[on?'add':'remove'](c);}};
  }
  setAttribute(k,v){this.attrs[k]=String(v); if(k==='id')nodes.set(v,this); if(k==='hidden')this.hidden=true;}
  getAttribute(k){return this.attrs[k]??null;}
  removeAttribute(k){delete this.attrs[k];}
  append(...items){this.children.push(...items);}
  prepend(...items){this.children.unshift(...items);}
  replaceChildren(...items){this.children=[...items];}
  set innerHTML(v){this.children=[];this.html=v;if(v.includes('<em>'))this.children.push(new Element('em'));} get innerHTML(){return this.html||'';}
  addEventListener(k,fn){(this.events[k]??=[]).push(fn);}
  removeEventListener(){}
  dispatch(type, fields={}){const e={type,button:0,isPrimary:true,pointerId:1,detail:1,clientX:0,clientY:0,preventDefault(){this.prevented=true;},...fields};for(const fn of this.events[type]||[])fn(e);return e;}
  click(){if(!this.disabled)this.dispatch('click',{detail:0});}
  getBoundingClientRect(){return {left:parseFloat(this.style.left)||0,top:parseFloat(this.style.top)||0,width:48,height:48};}
  setPointerCapture(id){this.capture=id;} hasPointerCapture(id){return this.capture===id;}
  releasePointerCapture(id){this.capture=null;this.dispatch('lostpointercapture',{pointerId:id});}
  querySelector(selector){return this.querySelectorAll(selector)[0]||null;}
  querySelectorAll(selector){return this.children.flatMap(all).filter(n=>selector.startsWith('.')?n.classList?.contains(selector.slice(1)):n.tagName===selector.toUpperCase());}
}
const context = vm.createContext({console, structuredClone, localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k)},
  document:{currentScript:null,readyState:'loading',addEventListener(){},getElementById:k=>nodes.get(k)||null,querySelector:()=>null,querySelectorAll:()=>[],createElement:tag=>new Element(tag),body:new Element('body')},
  window:{innerWidth:390,innerHeight:844},
  setTimeout:fn=>{timers.set(++timerId,fn);return timerId;},clearTimeout:id=>timers.delete(id),
  setInterval:fn=>{timers.set(++timerId,fn);return timerId;},clearInterval:id=>timers.delete(id),requestAnimationFrame:fn=>fn(),
  countOpen:()=>opens++,URL,AbortController});
context.window.setInterval=context.setInterval;context.window.setTimeout=context.setTimeout;context.window.clearInterval=context.clearInterval;
source = source.replace(/\}\)\(\);\s*$/, `
const originalResolveCompanions = resolveCharacterCompanions;
const originalResolvePlayer = resolveCharacterCompanionForPlayer;
window.test = {state, openCenter, closeCenter, openGame, renderHome, buildHeader, unoMakeDeck, unoNew, unoPlayable, unoApplyPlay, unoSave, unoLoad, unoCompanionTurn,
 newSpiderGame, renderSpider, match3New, match3Load, match3Save, match3NormalizeTile, match3RemoveCells, renderMatch3,
 getCharacterCompanionSettings, saveCharacterCompanionSettings, saveIdentityProfile, getPlayerProfile, getCompanionDisplayName, resolveCharacterCompanions, getCompanionAvatarSource, createIdentityEditor, createBoardCompanionChat, unoPlayerName, ddzPlayerName,
 stubCompanionSelection:()=>{resolveCharacterCompanions=()=>[{name:'Saved role'}];resolveCharacterCompanionForPlayer=()=>null;},
 restoreCompanionSelection:()=>{resolveCharacterCompanions=originalResolveCompanions;resolveCharacterCompanionForPlayer=originalResolvePlayer;},
 renderUno, bindFloatingDrag, setRestorePosition, getStoredLauncherPosition, setLauncherPosition,
 stubOpen:()=>{openCenter=()=>countOpen();},
 stubCompanion:(generate)=>{resolveCharacterCompanionForPlayer=()=>({name:'Test'});getLiveCompanionSettings=()=>({});generateCharacterCompanionAction=generate;}};
})();`);
vm.runInContext(source,context);
const api=context.window.test;
const results=[];
async function test(name,fn){if(process.env.STGC_TEST_FILTER&&!name.includes(process.env.STGC_TEST_FILTER))return;await fn();results.push(name);console.log('PASS '+name);}
function find(root,cls){return [root,...root.children.flatMap(n=>all(n))].filter(n=>n.classList?.contains(cls));}
function all(n){return [n,...(n.children||[]).flatMap(all)];}
function game(){const g=api.unoNew(); g.current=0;g.currentColor='red';g.discard=[{color:'red',type:'number',value:5}];g.hands[0]=[{color:'red',type:'number',value:3},{color:'blue',type:'number',value:5},{color:'wild',type:'wild',value:'变色'}];return g;}
(async()=>{
await test('UNO deck has 108 cards and 8 wild cards',()=>{const d=api.unoMakeDeck();assert.equal(d.length,108);assert.equal(d.filter(c=>c.color==='wild').length,8);});
await test('UNO initial deal conserves every card',()=>{const g=api.unoNew();assert.deepEqual(Array.from(g.hands,h=>h.length),[7,7,7,7]);assert.equal(g.deck.length+g.discard.length+28,108);});
await test('UNO color and number matching',()=>{const g=game();assert(api.unoPlayable(g.hands[0][0],g));assert(api.unoPlayable(g.hands[0][1],g));assert(!api.unoPlayable({color:'blue',type:'number',value:2},g));});
await test('UNO +4 cannot bypass a matching color',()=>{const g=game();assert(!api.unoPlayable({color:'wild',type:'wild4',value:'+4'},g,0));});
await test('UNO rejects wrong-turn, finished-game and invalid-index plays without mutation',()=>{for(const patch of [{current:1},{over:true},{}]){const g=Object.assign(game(),patch),before=JSON.stringify(g);assert.equal(api.unoApplyPlay(g,0,patch.current||patch.over?0:-1),false);assert.equal(JSON.stringify(g),before);}});
await test('UNO rejects stale pre-draw card selection',()=>{const g=game();g.drawnThisTurn=true;g.drawnCardIndex=2;assert.equal(api.unoApplyPlay(g,0,0),false);assert.equal(api.unoApplyPlay(g,0,2,'blue'),true);});
await test('UNO rejects invalid wildcard color',()=>{const g=game(),before=JSON.stringify(g);assert.equal(api.unoApplyPlay(g,0,2,'purple'),false);assert.equal(JSON.stringify(g),before);});
await test('UNO valid play advances the turn and conserves cards',()=>{const g=game(),n=g.hands[0].length;assert(api.unoApplyPlay(g,0,0));assert.equal(g.current,1);assert.equal(g.hands[0].length,n-1);assert.equal(g.discard.at(-1).value,3);});
await test('UNO reset hides stale wildcard picker; stale color cannot play',()=>{storage.clear();api.state.currentGame='uno';const g=game();api.unoSave(g);const body=new Element();api.renderUno(body);const wild=find(body,'uno-card').find(n=>n.classList.contains('wild'));wild.click();const picker=find(body,'uno-color-picker')[0];assert.equal(picker.hidden,false);all(body).find(n=>n.textContent==='重新开始').click();assert.equal(picker.hidden,true);assert.equal(picker.dataset.index,undefined);const before=JSON.stringify(api.state.uno);picker.children[0].click();assert.equal(JSON.stringify(api.state.uno),before);api.state.cleanup();api.state.cleanup=null;});
await test('UNO draw pile and toolbar share disabled state',()=>{storage.clear();const g=game();g.current=1;api.unoSave(g);const body=new Element();api.state.currentGame='uno';api.renderUno(body);assert.equal(find(body,'uno-deck')[0].disabled,true);api.state.cleanup();api.state.cleanup=null;});
await test('UNO finished hand does not expose playable buttons',()=>{storage.clear();const g=game();g.over=true;g.winner=1;api.unoSave(g);const body=new Element();api.state.currentGame='uno';api.renderUno(body);assert.equal(find(body,'playable').length,0);api.state.cleanup();api.state.cleanup=null;});
await test('UNO persisted card text is not interpreted as HTML',()=>{storage.clear();const g=game();g.hands[0][0].value='<img src=x onerror=alert(1)>';api.unoSave(g);const body=new Element();api.state.currentGame='uno';api.renderUno(body);assert(all(body).some(n=>n.textContent===g.hands[0][0].value));assert(!all(body).some(n=>n.innerHTML.includes('<img')));api.state.cleanup();api.state.cleanup=null;});
await test('Collapsed handle clamps to phone bounds and stores independent position',()=>{const handle=new Element();nodes.set('st-mini-game-center-restore',handle);api.setRestorePosition(9999,-10);assert.equal(handle.style.left,'378px');assert.equal(handle.style.top,'8px');assert.equal(JSON.parse(storage.get('stgc-restore-position-v1')).x,378);api.setRestorePosition(200,300,false);assert.equal(JSON.parse(storage.get('stgc-restore-position-v1')).x,378);});
await test('Corrupted launcher position is ignored',()=>{storage.set('stgc-launcher-position-v1','{"x":"bad","y":3}');assert.equal(api.getStoredLauncherPosition(),null);});
await test('Actual UNO header returns from an open overlay to the game menu',()=>{storage.clear();api.state.currentGame=null;api.state.lastGame=null;api.openCenter();api.openGame('uno');const root=nodes.get('st-mini-game-center');assert(root.classList.contains('show'));all(root).find(n=>n.attrs.title==='返回 Silly Game').click();assert.equal(api.state.currentGame,null);assert(find(root,'stgc-home-panel').length);assert.equal(api.state.cleanup,null);assert.equal(api.state.unoTimer,null);});
await test('Actual close button hides UNO, saves it and allows reopening',()=>{api.openGame('uno');let root=nodes.get('st-mini-game-center');const before=JSON.stringify(api.state.uno.hands);all(root).find(n=>n.attrs['aria-label']==='关闭 Silly Game').click();assert(!root.classList.contains('show'));assert.equal(api.state.currentGame,null);assert.equal(api.state.lastGame,'uno');api.openCenter();assert(root.classList.contains('show'));assert.equal(api.state.currentGame,'uno');assert.equal(JSON.stringify(api.state.uno.hands),before);api.closeCenter();});
await test('Every game header uses a working home navigation while the overlay is open',()=>{for(const id of ['uno','doudizhu','spider','gomoku','chess','xiangqi','sudoku','mines','2048','tetris','farm','match3','characterCompanion']){const root=nodes.get('st-mini-game-center');root.classList.add('show');api.state.currentGame=id;api.state.lastGame=id;const header=api.buildHeader({back:true,title:id});all(header).find(n=>n.attrs.title==='返回 Silly Game').click();assert.equal(api.state.currentGame,null,id);assert(find(root,'stgc-home-panel').length,id);}api.closeCenter();});
await test('Restart UNO stays on the same page and preserves local AI with saved roles',()=>{storage.clear();api.stubCompanionSelection();api.state.characterCompanion=null;const g=game();g.companion={enabled:false,settings:{}};api.unoSave(g);api.state.lastGame=null;api.openCenter();api.openGame('uno');const root=nodes.get('st-mini-game-center');assert.equal(api.state.uno.companion.enabled,false);const body=find(root,'stgc-game-body')[0];all(root).find(n=>n.textContent==='重新开始').click();assert.equal(api.state.currentGame,'uno');assert.equal(find(root,'stgc-game-body')[0],body);assert.equal(api.state.uno.companion.enabled,false);assert.equal(api.state.uno.hands[0].length,7);api.closeCenter();api.restoreCompanionSelection();});
await test('Reopening saved local UNO does not force companion mode from cached selections',()=>{storage.clear();api.stubCompanionSelection();api.state.characterCompanion={speak:true};const g=game();g.companion={enabled:false,settings:{}};api.unoSave(g);api.state.lastGame='uno';api.openCenter();assert.equal(api.state.uno.companion.enabled,false);api.closeCenter();api.state.characterCompanion=null;api.restoreCompanionSelection();});
await test('Restart UNO preserves companion mode, while explicit mode toggle controls it',()=>{storage.clear();api.stubCompanionSelection();const g=game();g.companion={enabled:true,settings:{}};api.unoSave(g);api.state.lastGame='uno';api.openCenter();const root=nodes.get('st-mini-game-center');all(root).find(n=>n.textContent==='重新开始').click();assert.equal(api.state.uno.companion.enabled,true);all(root).find(n=>n.tagName==='BUTTON'&&n.textContent.startsWith('角色陪玩 ·')).click();assert.equal(api.state.uno.companion.enabled,false);all(root).find(n=>n.textContent==='重新开始').click();assert.equal(api.state.uno.companion.enabled,false);api.closeCenter();api.state.characterCompanion=null;api.restoreCompanionSelection();});
await test('Doudizhu restart and reopen also preserve explicitly selected local AI',()=>{storage.clear();api.stubCompanionSelection();api.state.lastGame=null;api.openCenter();api.openGame('doudizhu');const root=nodes.get('st-mini-game-center');api.state.doudizhu.companion.enabled=false;api.state.characterCompanion={speak:true};all(root).find(n=>n.textContent==='重新开始').click();assert.equal(api.state.currentGame,'doudizhu');assert.equal(api.state.doudizhu.companion.enabled,false);api.closeCenter();api.openCenter();assert.equal(api.state.currentGame,'doudizhu');assert.equal(api.state.doudizhu.companion.enabled,false);api.closeCenter();api.state.characterCompanion=null;api.restoreCompanionSelection();});
await test('Duplicate launcher activation keeps the open game intact but back still works',()=>{storage.clear();api.state.lastGame=null;api.openCenter();api.openGame('uno');const root=nodes.get('st-mini-game-center'),body=find(root,'stgc-game-body')[0],g=api.state.uno;api.openCenter();assert.equal(find(root,'stgc-game-body')[0],body);assert.equal(api.state.uno,g);all(root).find(n=>n.attrs.title==='返回 Silly Game').click();assert.equal(api.state.currentGame,null);api.closeCenter();});
await test('Spider stock is outside and before the horizontally scrolling tableau',()=>{api.state.spider=null;api.state.currentGame='spider';const body=new Element();api.renderSpider(body);const area=find(body,'spider-area')[0],bar=find(body,'spider-bottom')[0];assert(find(bar,'spider-stock').length);assert.equal(find(area,'spider-stock').length,0);assert(body.children.indexOf(bar)<body.children.indexOf(area));api.state.cleanup();api.state.cleanup=null;});
await test('Spider stack sizing tracks every card after a stock deal',()=>{api.state.spider=null;api.state.currentGame='spider';const body=new Element();api.renderSpider(body);find(body,'spider-stock')[0].click();const cols=find(body,'spider-column');cols.forEach((col,i)=>assert.equal(col.style['--spider-stack-steps'],String(api.state.spider.tableau[i].length-1)));assert.equal(api.state.spider.stock.length,40);assert(find(body,'spider-card').every(c=>c.style['--card-offset'].includes('var(--spider-card-step)')));api.state.cleanup();api.state.cleanup=null;});
await test('Spider restart keeps its timer attached to the new game',()=>{timers.clear();api.state.spider=null;api.state.currentGame='spider';const body=new Element();api.renderSpider(body);all(body).find(n=>n.innerHTML.includes('重新开始')).click();api.state.spider.startedAt=Date.now()-6000;for(const fn of timers.values())fn();assert(api.state.spider.time>=5);api.state.cleanup();api.state.cleanup=null;});
await test('Match3 save/load retains jelly, ice, vine and extra moves',()=>{storage.clear();const g=api.match3New(1);g.board[0][0].jelly=true;g.board[0][1].ice=1;g.board[0][2].vine=1;g.maxMoves+=5;g.tools.extraMoves--;api.match3Save(g);const loaded=api.match3Load();assert(loaded.board[0][0].jelly);assert(loaded.board[0][1].ice);assert(loaded.board[0][2].vine);assert.equal(loaded.maxMoves,g.maxMoves);assert.equal(loaded.tools.extraMoves,g.tools.extraMoves);});
await test('Match3 extra moves and shuffle act on the tool button without a cell click',()=>{storage.clear();api.state.match3=null;api.state.currentGame='match3';const body=new Element();api.renderMatch3(body);const g=api.state.match3,moves=g.maxMoves,remaining=g.tools.extraMoves;find(body,'match3-tool-btn').find(n=>n.innerHTML.includes('+5 步')).click();assert.equal(g.maxMoves,moves+5);assert.equal(g.tools.extraMoves,remaining-1);assert.equal(g.tool,null);const shuffles=g.tools.shuffle;find(body,'match3-tool-btn').find(n=>n.innerHTML.includes('洗牌')).click();assert.equal(g.tools.shuffle,shuffles-1);assert.equal(g.tool,null);api.state.cleanup();api.state.cleanup=null;});
await test('Match3 art keeps special, jelly, ice and vine layers independent and labels cells',()=>{storage.clear();api.state.match3=api.match3New(1);Object.assign(api.state.match3.board[0][0],{special:'row',jelly:1,ice:1,vine:1});api.match3Save(api.state.match3);api.state.currentGame='match3';const body=new Element();api.renderMatch3(body);const cell=find(body,'match3-cell')[0];for(const cls of ['match3-candy-shape','match3-special-mark','match3-jelly-layer','match3-ice-layer','match3-vine-layer'])assert.equal(find(cell,cls).length,1,cls);assert(cell.attrs['aria-label'].includes('横向消除'));assert(cell.attrs['aria-label'].includes('果冻目标'));assert(body.classList.contains('match3-game-body'));api.state.cleanup();api.state.cleanup=null;});
await test('Match3 hammer/clear path counts obstacles instead of silently deleting objectives',()=>{const g=api.match3New(1);g.board[0][0].ice=1;g.board[0][2].vine=1;api.match3RemoveCells(g,[[0,0],[0,2]],1.5);assert.equal(g.iceBroken,1);assert.equal(g.vineBroken,1);assert(g.board[0][0]);assert(g.board[0][2]);assert(!g.board[0][0].ice);assert(!g.board[0][2].vine);});
await test('Player name/avatar persist without any selected companion slots',()=>{storage.clear();api.saveCharacterCompanionSettings({rateLimitPerMinute:17});api.saveIdentityProfile(null,{name:'  小鱼  ',avatar:'data:image/png;base64,avatar'});const saved=api.getCharacterCompanionSettings();assert.equal(saved.playerProfile.name,'小鱼');assert.equal(saved.playerProfile.avatar,'data:image/png;base64,avatar');assert.equal(saved.rateLimitPerMinute,17);assert.equal(saved.companionSlots,null);api.state.characterCompanion=null;assert.equal(api.getPlayerProfile().name,'小鱼');assert.equal(api.unoPlayerName({},0),'小鱼');assert.equal(api.ddzPlayerName({},0),'小鱼');});
await test('Character and worldbook names and avatars are saved independently',()=>{storage.clear();const chars=[{name:'原角色',description:'original description',avatar:'/original.png',character_book:{entries:[{uid:7,name:'原条目',content:'entry description'}]}}];context.window.SillyTavern={getContext:()=>({characters:chars,characterId:0})};const character={source:'character',characterIndex:0},entry={source:'worldbook',characterIndex:0,entryIndex:0,entryId:'7'};api.saveCharacterCompanionSettings({companionSlots:[character,entry]});api.saveIdentityProfile(character,{name:'角色昵称',avatar:'/custom-character.png'});api.saveIdentityProfile(entry,{name:'条目昵称',avatar:'/custom-entry.png'});const resolved=api.resolveCharacterCompanions();assert.equal(resolved[0].name,'角色昵称');assert.equal(resolved[1].name,'条目昵称');assert.equal(api.getCompanionAvatarSource(resolved[0]),'/custom-character.png');assert.equal(api.getCompanionAvatarSource(resolved[1]),'/custom-entry.png');assert.equal(chars[0].name,'原角色');api.saveIdentityProfile(character,{name:'新昵称'});assert.equal(api.getCompanionAvatarSource(api.resolveCharacterCompanions()[0]),'/custom-character.png');api.saveIdentityProfile(character,{},true);assert.equal(api.resolveCharacterCompanions()[0].name,'原角色');assert.equal(api.resolveCharacterCompanions()[1].name,'条目昵称');delete context.window.SillyTavern;});
await test('Profile save button persists text, reset clears only player profile',()=>{storage.clear();api.saveIdentityProfile({source:'character',characterIndex:0},{name:'角色保留'});const editor=api.createIdentityEditor();const input=all(editor).find(n=>n.attrs['aria-label']==='自定义显示名字');input.value='玩家名';all(editor).find(n=>n.textContent==='保存名字与头像').click();assert.equal(api.getPlayerProfile().name,'玩家名');assert.equal(find(editor,'stgc-identity-status')[0].textContent,'已保存');all(editor).find(n=>n.textContent==='恢复默认').click();assert.equal(api.getPlayerProfile().name,'你');assert.equal(api.getCompanionDisplayName({source:'character',characterIndex:0},'原名'),'角色保留');});
await test('Full storage reports profile save failure without a false success',()=>{storage.clear();api.saveIdentityProfile(null,{name:'旧名字'});const editor=api.createIdentityEditor();all(editor).find(n=>n.attrs['aria-label']==='自定义显示名字').value='新名字';const original=context.localStorage.setItem;try{context.localStorage.setItem=()=>{throw new Error('QuotaExceededError');};all(editor).find(n=>n.textContent==='保存名字与头像').click();assert(find(editor,'stgc-identity-status')[0].textContent.includes('保存失败'));assert.equal(api.getPlayerProfile().name,'旧名字');}finally{context.localStorage.setItem=original;}});
await test('UNO player identity and color picker have their own layout positions',()=>{storage.clear();api.saveIdentityProfile(null,{name:'玩家 UNO',avatar:'/player.png'});api.state.uno=null;api.state.currentGame='uno';const body=new Element();api.renderUno(body);assert.equal(find(body,'stgc-player-name')[0].textContent,'玩家 UNO');const picker=find(body,'uno-color-picker')[0];assert(find(body,'uno-table')[0].children.includes(picker));assert(!find(body,'uno-top-area')[0].children.includes(picker));api.state.cleanup();api.state.cleanup=null;});
await test('Chess profile strip is before the board and reflects custom character identity',()=>{storage.clear();context.window.SillyTavern={getContext:()=>({characters:[{name:'原名',avatar:'/original.png'}],characterId:0})};api.saveIdentityProfile({source:'character',characterIndex:0},{name:'大头像角色',avatar:'/big.png'});const body=new Element(),board=new Element();board.className='test-board';body.append(board);const cleanup=api.createBoardCompanionChat(body,()=>({mode:'role',companion:{enabled:true}}));assert(body.children[0].classList.contains('stgc-board-companion-header'));assert.equal(body.children[1],board);assert.equal(find(body,'stgc-board-companion-title')[0].textContent,'大头像角色');assert.equal(find(body,'stgc-board-companion-avatar')[0].src,'/big.png');assert(!find(body,'stgc-board-companion-avatar-wrap')[0].children.some(n=>n.classList.contains('stgc-companion-speech-bubble')));cleanup();delete context.window.SillyTavern;});
await test('Small handle docks on either edge and remembers the side on reload',()=>{const handle=nodes.get('st-mini-game-center-restore');api.setRestorePosition(10,120);assert.equal(handle.style.left,'-6px');assert.equal(api.getStoredLauncherPosition('stgc-restore-position-v1').edge,'left');api.setRestorePosition(300,120,false);assert.equal(handle.style.left,'300px');api.setRestorePosition(300,120);const saved=api.getStoredLauncherPosition('stgc-restore-position-v1');assert.equal(saved.edge,'right');context.window.innerWidth=844;api.setRestorePosition(saved.edge==='right'?844:0,saved.y,false,true);assert.equal(handle.style.left,'832px');context.window.innerWidth=390;});
api.stubOpen();
await test('Mouse drag saves once, suppresses click, and releases pointer',()=>{const e=new Element(),saved=[];api.bindFloatingDrag(e,(x,y,save=true)=>{e.style.left=x+'px';e.style.top=y+'px';saved.push(save);});const before=opens;e.dispatch('pointerdown',{clientX:10,clientY:10});e.dispatch('pointermove',{clientX:100,clientY:90});e.dispatch('pointerup');e.dispatch('click');assert.equal(opens,before);assert.deepEqual(saved,[false,true]);assert.equal(e.capture,null);});
await test('Touch tap and keyboard open normally after a drag',()=>{const e=new Element();api.bindFloatingDrag(e,()=>{});const before=opens;e.dispatch('pointerdown',{pointerType:'touch'});e.dispatch('pointermove',{clientX:3,clientY:2});e.dispatch('pointerup');e.dispatch('click');e.dispatch('keydown',{key:'Enter'});assert.equal(opens,before+2);});
await test('Pointer cancellation never opens the game',()=>{const e=new Element();api.bindFloatingDrag(e,()=>{});const before=opens;e.dispatch('pointerdown');e.dispatch('pointercancel');e.dispatch('click');assert.equal(opens,before);});
await test('Secondary pointer cannot replace an active drag',()=>{const e=new Element(),pos=[];api.bindFloatingDrag(e,(x,y)=>pos.push([x,y]));e.dispatch('pointerdown',{pointerId:1});e.dispatch('pointerdown',{pointerId:2,isPrimary:false});e.dispatch('pointermove',{pointerId:2,clientX:100});assert.equal(pos.length,0);e.dispatch('pointermove',{pointerId:1,clientX:20});assert.equal(pos.length,1);});
await test('Rejected UNO request after leaving cannot mutate or save old game',async()=>{timers.clear();storage.clear();const g=game();g.current=1;g.companion={enabled:true,settings:{}};api.state.uno=g;api.state.currentGame='uno';let reject;api.stubCompanion(()=>new Promise((_,r)=>reject=r));const promise=api.unoCompanionTurn(g,()=>{});api.state.currentGame=null;const before=JSON.stringify(g);reject(new Error('expected'));await promise;assert.equal(JSON.stringify(g),before);assert.equal(storage.has('silly-game:uno:v1'),false);assert.equal(timers.size,0);});
await test('Second UNO response after exit cannot play, save, redraw or schedule',async()=>{timers.clear();storage.clear();const g=game();g.current=1;g.companion={enabled:true,settings:{}};g.deck=[{color:'red',type:'number',value:7}];api.state.uno=g;api.state.currentGame='uno';let resolveSecond,calls=0;api.stubCompanion(()=>++calls===1?Promise.resolve({action:'draw'}):new Promise(r=>resolveSecond=r));const promise=api.unoCompanionTurn(g,()=>{});for(let i=0;i<5&&!resolveSecond;i++)await Promise.resolve();assert(resolveSecond);api.state.unoSession++;const before=JSON.stringify(g);resolveSecond({action:'play',cardIndex:g.hands[1].length-1});await promise;assert.equal(JSON.stringify(g),before);assert.equal(storage.has('silly-game:uno:v1'),false);assert.equal(timers.size,0);});
await test('Theme selectors do not globally override semantic span/strong/b colors',()=>{const css=fs.readFileSync(path.join(sourceDir,'style.css'),'utf8');for(const tag of ['span','strong','b'])assert(!new RegExp('#st-mini-game-center '+tag+'[ ,{\\n]').test(css));assert(css.includes('#st-mini-game-center .ddz-card-red { color: #b4233c; }'));assert(css.includes('#st-mini-game-center [hidden] { display: none !important; }'));});
fs.writeFileSync(path.join(__dirname,'test-results.json'),JSON.stringify({passed:results.length,tests:results,scope:'Node VM + DOM stubs; no browser visual or live SillyTavern/API verification'},null,2));
console.log('TOTAL '+results.length+' PASSED');
})().catch(e=>{console.error(e);process.exitCode=1;});
